import { JnvDict } from "../../types";

export const regionState : JnvDict = {
  Bhopal: ['Chhattisgarh', 'Madhya Pradesh', 'Orissa'],
  Lucknow: ['Uttarakhand', 'Uttar Pradesh'],
  Chandigarh: ['Chandigarh',
    'Himachal Pradesh',
    'Jammu & Kashmir',
    'Ladakh',
    'Punjab'],
  Shillong: ['Arunachal Pradesh',
    'Assam',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Sikkim',
    'Tripura'],
  Pune: ['Dadra & Nagar Haveli',
    'Daman & Diu',
    'Goa',
    'Gujarat',
    'Maharashtra'],
  Patna: ['Bihar', 'Jharkhand', 'West Bengal'],
  Hyderabad: ['Andhra Pradesh',
    'Andaman and Nicobar Islands',
    'Karnataka',
    'Kerala',
    'Lakshadweep',
    'Pondicherry',
    'Telangana'],
  Jaipur: ['Delhi', 'Haryana', 'Rajasthan']
}
